package api

// OrderSide ...
type OrderSide = string

// LongSide ...
const LongSide OrderSide = "buy"

// ShortSide ...
const ShortSide OrderSide = "sell"

// OrderType ...
type OrderType = string

// LimitType ...
const LimitType = "limit"

// StopType ...
const StopType = "stop"

// MarketType ...
const MarketType = "market"
