package api

// OrderSide ...
type OrderSide = string

// LongSide ...
const LongSide OrderSide = "buy"

// ShortSide ...
const ShortSide OrderSide = "sell"

// OrderType ...
type OrderType = string

// LimitType ...
const LimitType OrderType = "limit"

// StopType ...
const StopType OrderType = "stop"

// MarketType ...
const MarketType = "market"
